### ISSUE TITLE
[vm-other] Chris get VM image working in VirtualBox

### ISSUE THREAD

**Issue by chbrown13** [SoftwareEngineeringToolDemos/ICSE-2012-DSOL#6]
I get the following errpr whenever I try to upload the DSOL .ova image into Virtual Box on my machine.

![image](https://cloud.githubusercontent.com/assets/4522684/10554231/b16c066a-742f-11e5-8d9a-b42acef7ccee.png)

**Comment by chbrown13** [comment]
Fixed the error and able to load the DSOL VM image properly after following these instructions: https://forums.virtualbox.org/viewtopic.php?f=1&t=62339

Thanks @jodeck80

**Comment by jodeck80** [comment]
Awesome! @chbrown13
